services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
      - SERVER_PORT=${PORT:-8080}
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/biblioteca
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-sa}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - h2-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
        reservations:
          memory: '256M'

volumes:
  h2-data:
    driver: localta: